"""Train, calibrate and evaluate the fire forecast; write the report (make forecast-train)."""

import logging
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta

import httpx
import joblib
import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.inspection import permutation_importance
from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import average_precision_score, brier_score_loss, roc_auc_score

from app.boundaries import allowed_area
from app.config import REPO_ROOT, get_thresholds
from app.db import session_factory
from app.forecast.dataset import (
    FEATURES,
    Table,
    build_grid,
    build_table,
    fire_days,
    prepare,
    weather_point,
)
from app.forecast.weather_history import fetch_point
from app.logging_setup import configure_logging

log = logging.getLogger("forecast")

# Negatives are ~99 % of cell-days. Training on all positives and a quarter of the negatives
# (weighted x4) gives the same model in a quarter of the time and memory; isotonic calibration on
# the untouched validation years fixes the probabilities afterwards. Rows are sampled while the
# table is built (dataset.build_table), so the full table never exists in memory.
NEGATIVE_SHARE = 0.25
TOP_SHARE = 0.05
# Enough rows to rank features; more only adds minutes.
IMPORTANCE_SAMPLE = 100_000
BASELINES = {
    "climatology": "cell_month_fire_rate",
    "fwi": "fwi",
    "persistence": "fire_days_around_7d",
}


@dataclass(frozen=True)
class Scores:
    pr_auc: float
    roc_auc: float
    brier: float
    caught_in_top: float  # share of fires inside the top 5 % riskiest cell-days


def evaluate(y: np.ndarray, p: np.ndarray) -> Scores:
    cutoff = np.quantile(p, 1 - TOP_SHARE)
    return Scores(
        pr_auc=average_precision_score(y, p),
        roc_auc=roc_auc_score(y, p),
        brier=brier_score_loss(y, p),
        caught_in_top=float(y[p >= cutoff].sum() / max(y.sum(), 1)),
    )


PREDICT_CHUNK = 250_000


def predict(model: HistGradientBoostingClassifier, X: np.ndarray) -> np.ndarray:
    """In chunks: scikit-learn converts its input to float64, which would double a large table."""
    return np.concatenate(
        [
            model.predict_proba(X[i : i + PREDICT_CHUNK])[:, 1]
            for i in range(0, len(X), PREDICT_CHUNK)
        ]
    )


def train_horizon(tables: dict[str, Table], horizon: int, rng: np.random.Generator) -> dict:
    train, valid, test = tables["train"], tables["validation"], tables["test"]
    model = HistGradientBoostingClassifier(
        learning_rate=0.06,
        max_iter=400,
        max_leaf_nodes=31,
        l2_regularization=1.0,
        early_stopping=True,
        random_state=0,
    )
    log.info("horizon %s: training on %s cell-days", horizon, len(train.X))
    model.fit(train.X, train.y[horizon], sample_weight=train.weight)

    calibration = IsotonicRegression(out_of_bounds="clip", y_min=0, y_max=1)
    calibration.fit(predict(model, valid.X), valid.y[horizon])
    y_test = test.y[horizon]
    results = {"model": evaluate(y_test, calibration.predict(predict(model, test.X)))}

    for name, feature in BASELINES.items():
        column = FEATURES.index(feature)
        baseline = IsotonicRegression(out_of_bounds="clip", y_min=0, y_max=1)
        baseline.fit(np.nan_to_num(valid.X[:, column]), valid.y[horizon])
        results[name] = evaluate(y_test, baseline.predict(np.nan_to_num(test.X[:, column])))

    sample = rng.choice(len(test.X), size=min(IMPORTANCE_SAMPLE, len(test.X)), replace=False)
    importance = permutation_importance(
        model,
        test.X[sample],
        y_test[sample],
        scoring="average_precision",
        n_repeats=3,
        random_state=0,
    )
    return {
        "horizon": horizon,
        "model": model,
        "calibration": calibration,
        "scores": results,
        "importance": dict(zip(FEATURES, importance.importances_mean.tolist(), strict=True)),
        "base_rate": float(y_test.mean()),
        "test_positives": int(y_test.sum()),
        "train_rows": len(train.X),
    }


def report(results: list[dict], config: dict, cells: int, days: int) -> str:
    lines = [
        "# Fire forecast evaluation",
        "",
        f"Generated by `make forecast-train` on {datetime.now(UTC):%Y-%m-%d}. "
        "Spec: [05-fire-forecast](../05-fire-forecast.md).",
        "",
        f"- Cells: {cells} of 0.1° in Argentina inside the region; {days} days.",
        f"- Train {config['train_years'][0]}–{config['train_years'][1]}, calibrate on "
        f"{config['validation_years'][0]}–{config['validation_years'][1]}, "
        f"test on {config['test_years'][0]}–{config['test_years'][1]}.",
        "- PR-AUC: higher is better; compare it with the base rate (a random guess scores the base "
        "rate). Brier: lower is better. Top 5 %: share of the test fires that fell in the 5 % of "
        "cell-days the method ranked riskiest.",
        "",
    ]
    for r in results:
        scores = r["scores"]
        beats = all(scores["model"].pr_auc > scores[b].pr_auc for b in BASELINES)
        lines += [
            f"## Next {r['horizon']} day{'s' if r['horizon'] > 1 else ''}",
            "",
            f"Base rate {r['base_rate']:.4f} "
            f"({r['test_positives']} fire cell-days in the test year). "
            f"**Beats every baseline on PR-AUC: {'yes' if beats else 'no'}.**",
            "",
            "| Method | PR-AUC | ROC-AUC | Brier | Fires in top 5 % |",
            "|---|---|---|---|---|",
        ]
        for name, s in scores.items():
            cells = [
                f"{s.pr_auc:.3f}",
                f"{s.roc_auc:.3f}",
                f"{s.brier:.5f}",
                f"{s.caught_in_top:.0%}",
            ]
            lines.append(f"| {name} | {' | '.join(cells)} |")
        top = sorted(r["importance"].items(), key=lambda kv: kv[1], reverse=True)[:6]
        lines += ["", "Most important features (drop in PR-AUC when shuffled):", ""]
        lines += [f"- `{name}`: {value:.4f}" for name, value in top]
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    configure_logging()
    thresholds = get_thresholds()
    config = thresholds["forecast"]
    boundary = thresholds["territories"]["allowed_area"]
    grid = build_grid(
        thresholds["region"]["bbox"], config["cell_degrees"], allowed_area(boundary, 0)
    )
    first, last = date(config["first_year"], 1, 1), date(config["last_year"], 12, 31)
    days = [first + timedelta(days=i) for i in range((last - first).days + 1)]

    points = {
        weather_point(*grid.center(r, c), config["weather_degrees"])
        for r, c in np.argwhere(grid.mask)
    }
    log.info("%s cells, %s weather points, %s days", int(grid.mask.sum()), len(points), len(days))
    with httpx.Client() as client:
        weather = {
            p: fetch_point(
                client,
                config["weather_url"],
                p[0],
                p[1],
                first,
                last,
                REPO_ROOT / config["weather_cache_dir"],
            )
            for p in sorted(points)
        }
    with session_factory()() as session:
        fire = fire_days(session, grid, days)
    log.info("%s fire cell-days", int(fire[grid.mask].sum()))

    rng = np.random.default_rng(0)
    inputs = prepare(
        grid,
        days,
        weather,
        fire,
        config["horizons_days"],
        config["weather_degrees"],
        config["rain_day_mm"],
    )
    tables = {
        "train": build_table(inputs, tuple(config["train_years"]), NEGATIVE_SHARE, rng),
        "validation": build_table(inputs, tuple(config["validation_years"]), 1.0, rng),
        "test": build_table(inputs, tuple(config["test_years"]), 1.0, rng),
    }
    # The tables hold everything training needs; drop the grid-sized inputs before fitting.
    del inputs, weather, fire
    results = [train_horizon(tables, h, rng) for h in config["horizons_days"]]

    model_dir = REPO_ROOT / config["model_dir"]
    model_dir.mkdir(parents=True, exist_ok=True)
    for r in results:
        joblib.dump(
            {
                "model": r["model"],
                "calibration": r["calibration"],
                "features": FEATURES,
                "horizon_days": r["horizon"],
                "trained_at": datetime.now(UTC).isoformat(),
                "config": config,
            },
            model_dir / f"fire_forecast_h{r['horizon']}.joblib",
        )
    path = REPO_ROOT / config["report"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report(results, config, int(grid.mask.sum()), len(days)))
    log.info("report written to %s", path)


if __name__ == "__main__":
    main()
