/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description The link in the email: signs in and goes back to the map.
         */
        get: operations["callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Emails a sign-in link. The answer is the same for every address (docs/09).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Me */
        patch: operations["change_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/me/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summary Now
         * @description Sends the account's summary at once (docs/09-accounts-and-alerts.md#summaries).
         */
        post: operations["summary_now_auth_me_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boundary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Boundary
         * @description Argentina, simplified to about 1 km: the map grays out everything else while drawing.
         */
        get: operations["boundary_boundary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cadastre/parcel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parcel
         * @description The official parcel at a point, to draw a field from it (docs/08-cadastre.md).
         */
        get: operations["parcel_cadastre_parcel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cadastre/snap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Snap
         * @description A hand-drawn outline fitted to the property lines, or unchanged (docs/08-cadastre.md).
         */
        post: operations["snap_cadastre_snap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect
         * @description The outline of the field under a point, from a year of Sentinel-2 images (docs/10).
         */
        post: operations["detect_fields_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fire-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fire Events */
        get: operations["fire_events_fire_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk-events/{risk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Risk Status */
        patch: operations["update_risk_status_risk_events__risk_id__patch"];
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: operations["list__tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Color */
        patch: operations["change_color_tags__tag_id__patch"];
        trace?: never;
    };
    "/territories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: operations["list__territories_get"];
        put?: never;
        /** Create */
        post: operations["create_territories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_territories__territory_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_territories__territory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anomalies
         * @description The field's unusual patches as GeoJSON, to draw on the map (docs/11).
         */
        get: operations["anomalies_territories__territory_id__anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/fire-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fire History */
        get: operations["fire_history_territories__territory_id__fire_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Outline */
        patch: operations["change_outline_territories__territory_id__outline_patch"];
        trace?: never;
    };
    "/territories/{territory_id}/risk-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Events */
        get: operations["risk_events_territories__territory_id__risk_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Settings */
        patch: operations["change_settings_territories__territory_id__settings_patch"];
        trace?: never;
    };
    "/territories/{territory_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshots
         * @description The field's satellite photos, or a lot's field's (docs/12-field-page.md).
         */
        get: operations["snapshots_territories__territory_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/snapshots/{day}/{view}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot Image */
        get: operations["snapshot_image_territories__territory_id__snapshots__day___view__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/spray-conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spray Conditions */
        get: operations["spray_conditions_territories__territory_id__spray_conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{territory_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Tags */
        put: operations["replace_tags_territories__territory_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/{layer}/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tile */
        get: operations["tile_tiles__layer___z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyAnswerOut */
        AnomalyAnswerOut: {
            /**
             * Checked At
             * @description None until the field is first looked at
             */
            checked_at: string | null;
            data_quality: components["schemas"]["DataQuality"];
            /** Observed On */
            observed_on: string | null;
            /** Patches */
            patches: components["schemas"]["AnomalyPatchOut"][];
        };
        /** AnomalyPatchOut */
        AnomalyPatchOut: {
            /** Area Ha */
            area_ha: number;
            /**
             * Kind
             * @description less_green, water or burnt
             */
            kind: string;
            /**
             * Lot
             * @description The lot it is in, for a field split into lots
             */
            lot?: string | null;
            /**
             * Where
             * @description Compass point from the field's center, or center
             */
            where: string;
        };
        /**
         * DataQuality
         * @enum {string}
         */
        DataQuality: "GOOD" | "PARTIAL" | "STALE" | "CLOUD_OBSCURED" | "NO_DATA";
        /** DetectIn */
        DetectIn: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** DetectOut */
        DetectOut: {
            /**
             * Dates
             * @description Clear Sentinel-2 dates the outline was found in
             */
            dates: number;
            /**
             * First
             * Format: date
             */
            first: string;
            /**
             * Geometry
             * @description GeoJSON Polygon, EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
            /**
             * Last
             * Format: date
             */
            last: string;
        };
        /** FireAnswerOut */
        FireAnswerOut: {
            /** Acquired At */
            acquired_at: string | null;
            /** Confidence */
            confidence: string | null;
            data_quality: components["schemas"]["DataQuality"];
            /** Direction */
            direction: string | null;
            /** Distance M */
            distance_m: number | null;
            /** Fire Event Id */
            fire_event_id: number | null;
            /** Last Read At */
            last_read_at: string | null;
            /** Other Fires */
            other_fires: number;
            /** Received At */
            received_at: string | null;
            /** Sensors */
            sensors: string[];
            severity: components["schemas"]["Severity"] | null;
        };
        /** FireDayOut */
        FireDayOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Distance M */
            distance_m: number;
        };
        /** FireEventOut */
        FireEventOut: {
            /** Confidence */
            confidence: string;
            /**
             * First Detected At
             * Format: date-time
             */
            first_detected_at: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Last Detected At
             * Format: date-time
             */
            last_detected_at: string;
            /** Max Frp Mw */
            max_frp_mw: number | null;
            /** Observation Count */
            observation_count: number;
            /** Processing Version */
            processing_version: string;
            /** Sensors */
            sensors: string[];
            status: components["schemas"]["FireEventStatus"];
        };
        /**
         * FireEventStatus
         * @enum {string}
         */
        FireEventStatus: "ACTIVE" | "STALE" | "CLOSED";
        /** FireHistoryOut */
        FireHistoryOut: {
            /** Days Per Month */
            days_per_month: number[];
            /** Days Per Year */
            days_per_year: {
                [key: string]: number;
            };
            /** Fire Days */
            fire_days: number;
            /** First Year */
            first_year: number;
            /** Inside Days */
            inside_days: number;
            /** Last Year */
            last_year: number;
            latest: components["schemas"]["FireDayOut"] | null;
            nearest: components["schemas"]["FireDayOut"] | null;
            /** Radius M */
            radius_m: number;
            /** Years Loaded */
            years_loaded: number[];
        };
        /** ForecastAnswerOut */
        ForecastAnswerOut: {
            data_quality: components["schemas"]["DataQuality"];
            /** Days */
            days: components["schemas"]["ForecastDayOut"][];
            /** Issued At */
            issued_at: string | null;
        };
        /** ForecastDayOut */
        ForecastDayOut: {
            /** Band */
            band: string;
            /** Factors */
            factors: components["schemas"]["ForecastFactorOut"][];
            /** Horizon Days */
            horizon_days: number;
            /** Probability */
            probability: number;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
        };
        /** ForecastFactorOut */
        ForecastFactorOut: {
            /** Code */
            code: string;
            /** Value */
            value: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: boolean;
            fire_data_quality: components["schemas"]["DataQuality"];
            latest_pass: components["schemas"]["LatestPassOut"] | null;
            latest_scan: components["schemas"]["LatestPassOut"] | null;
            /** Processing Version */
            processing_version: string;
            /** Sources */
            sources: components["schemas"]["SourceStatusOut"][];
        };
        /** LatestPassOut */
        LatestPassOut: {
            /**
             * Acquired At
             * Format: date-time
             */
            acquired_at: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Satellite */
            satellite: string;
            /** Sensor */
            sensor: string;
        };
        /**
         * Layer
         * @enum {string}
         */
        Layer: "territories" | "fire_events" | "observations" | "lightning" | "risk" | "parcels";
        /** LightningAnswerOut */
        LightningAnswerOut: {
            data_quality: components["schemas"]["DataQuality"];
            /** Flashes */
            flashes: number;
            /** Last At */
            last_at: string | null;
            /** Nearest M */
            nearest_m: number | null;
            /** Window Minutes */
            window_minutes: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /**
             * Locale
             * @default es
             * @enum {string}
             */
            locale: "es" | "en";
        };
        /** MeIn */
        MeIn: {
            summary: components["schemas"]["SummaryFrequency"];
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** Locale */
            locale: string;
            summary: components["schemas"]["SummaryFrequency"];
        };
        /** OutlineIn */
        OutlineIn: {
            /**
             * Geometry
             * @description GeoJSON Polygon of the piece, EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
            /**
             * Operation
             * @enum {string}
             */
            operation: "add" | "remove";
            /**
             * Preview
             * @description Answer with the result without saving it
             * @default false
             */
            preview: boolean;
        };
        /** PortfolioEntryOut */
        PortfolioEntryOut: {
            /** Alerts */
            alerts: boolean;
            anomaly: components["schemas"]["AnomalyAnswerOut"];
            fire: components["schemas"]["FireAnswerOut"];
            forecast: components["schemas"]["ForecastAnswerOut"];
            /** Hectares */
            hectares: number;
            kind: components["schemas"]["TerritoryKind"];
            lightning: components["schemas"]["LightningAnswerOut"];
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            priority: components["schemas"]["Priority"];
            spray: components["schemas"]["SprayAnswerOut"];
            /** Tags */
            tags: string[];
            /** Territory Id */
            territory_id: number;
            /** Visible */
            visible: boolean;
            weather: components["schemas"]["WeatherAnswerOut"];
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "HIGH" | "NORMAL" | "LOW";
        /** RiskEventOut */
        RiskEventOut: {
            /** Direction */
            direction: string | null;
            /** Distance M */
            distance_m: number;
            /** Factors */
            factors: {
                [key: string]: unknown;
            };
            /** Fire Event Id */
            fire_event_id: number;
            /** Id */
            id: number;
            /** Processing Version */
            processing_version: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["RiskStatus"];
            /** Territory Id */
            territory_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RiskStatus
         * @enum {string}
         */
        RiskStatus: "NEW" | "SEEN" | "RESOLVED";
        /** RiskStatusIn */
        RiskStatusIn: {
            status: components["schemas"]["RiskStatus"];
        };
        /**
         * RuleStatus
         * @enum {string}
         */
        RuleStatus: "PASS" | "CAUTION" | "FAIL" | "UNKNOWN";
        /**
         * SettingsIn
         * @description Only the settings given are changed.
         */
        SettingsIn: {
            /** Alerts */
            alerts?: boolean | null;
            priority?: components["schemas"]["Priority"] | null;
            /** Visible */
            visible?: boolean | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "CRITICAL" | "VERY_HIGH" | "HIGH" | "WATCH";
        /** SnapIn */
        SnapIn: {
            /**
             * Geometry
             * @description GeoJSON Polygon drawn by hand, EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** SnapOut */
        SnapOut: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /**
             * Method
             * @description parcels, edges or none
             */
            method: string;
            /** Parcels */
            parcels: {
                [key: string]: unknown;
            }[];
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Cloud Share */
            cloud_share: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Ndvi Mean */
            ndvi_mean: number | null;
        };
        /** SnapshotOutlineOut */
        SnapshotOutlineOut: {
            kind: components["schemas"]["TerritoryKind"];
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Territory Id */
            territory_id: number;
        };
        /**
         * SnapshotsOut
         * @description A field's satellite photos, oldest first (docs/12-field-page.md). A lot answers with its
         *     field's photos; `field_id` is the field whose images to load.
         */
        SnapshotsOut: {
            /** Field Id */
            field_id: number;
            /** Height */
            height: number;
            /** Outlines */
            outlines: components["schemas"]["SnapshotOutlineOut"][];
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotOut"][];
            /** Width */
            width: number;
        };
        /** SourceStatusOut */
        SourceStatusOut: {
            /** Last Error */
            last_error: string | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Run Status */
            last_run_status: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Product */
            product: string;
            /** Provider */
            provider: string;
        };
        /** SprayAnswerOut */
        SprayAnswerOut: {
            data_quality: components["schemas"]["DataQuality"];
            /** Drift Toward */
            drift_toward: string | null;
            /** Next Favorable */
            next_favorable: [
                string,
                string
            ] | null;
            /** Problems */
            problems: components["schemas"]["SprayRuleOut"][];
            /** Profile */
            profile: string;
            status: components["schemas"]["SprayStatus"] | null;
            /** Valid At */
            valid_at: string | null;
        };
        /** SprayHourOut */
        SprayHourOut: {
            data_quality: components["schemas"]["DataQuality"];
            /**
             * Forecast Fetched At
             * Format: date-time
             */
            forecast_fetched_at: string;
            /** Processing Version */
            processing_version: string;
            /** Rules */
            rules: components["schemas"]["SprayRuleOut"][];
            status: components["schemas"]["SprayStatus"];
            /**
             * Valid At
             * Format: date-time
             */
            valid_at: string;
            /** Weather */
            weather: {
                [key: string]: unknown;
            };
        };
        /**
         * SprayRuleOut
         * @description Codes and numbers only; the frontend writes the sentence in the user's language.
         */
        SprayRuleOut: {
            /**
             * Estimated
             * @default false
             */
            estimated: boolean;
            /** Limit */
            limit?: number | null;
            /** Rule */
            rule: string;
            status: components["schemas"]["RuleStatus"];
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
            /** Window H */
            window_h?: number | null;
        };
        /**
         * SprayStatus
         * @enum {string}
         */
        SprayStatus: "FAVORABLE" | "CAUTION" | "UNFAVORABLE";
        /**
         * SummaryFrequency
         * @enum {string}
         */
        SummaryFrequency: "WEEKLY" | "DAILY" | "OFF";
        /** TagColorIn */
        TagColorIn: {
            /**
             * Color
             * @description One of the palette colors, #rrggbb
             */
            color: string;
        };
        /** TagOut */
        TagOut: {
            /** Color */
            color: string;
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** TagsIn */
        TagsIn: {
            /** Tags */
            tags: string[];
        };
        /** TagsOut */
        TagsOut: {
            /**
             * Palette
             * @description The colors a tag can take, in order
             */
            palette: string[];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /** TerritoryIn */
        TerritoryIn: {
            /**
             * Cadastre
             * @description The parcel the outline came from (province, department, partida, plano)
             */
            cadastre?: {
                [key: string]: unknown;
            } | null;
            /**
             * Geometry
             * @description GeoJSON Polygon or MultiPolygon, EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Parent Id
             * @description Field id, to create a section
             */
            parent_id?: number | null;
            /**
             * Tags
             * @description key:value or plain labels
             */
            tags?: string[];
        };
        /**
         * TerritoryKind
         * @enum {string}
         */
        TerritoryKind: "FIELD" | "SECTION";
        /** TerritoryOut */
        TerritoryOut: {
            /** Alerts */
            alerts: boolean;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Hectares */
            hectares: number;
            /** Id */
            id: number;
            kind: components["schemas"]["TerritoryKind"];
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            priority: components["schemas"]["Priority"];
            /** Tags */
            tags: string[];
            /** Visible */
            visible: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherAnswerOut */
        WeatherAnswerOut: {
            /** Cloud Cover Pct */
            cloud_cover_pct: number | null;
            data_quality: components["schemas"]["DataQuality"];
            /** Rain 24H Mm */
            rain_24h_mm: number | null;
            /**
             * Rain Probability Pct
             * @description Highest in the next 24 hours
             */
            rain_probability_pct: number | null;
            /** Relative Humidity Pct */
            relative_humidity_pct: number | null;
            /** Temperature C */
            temperature_c: number | null;
            /** Valid At */
            valid_at: string | null;
            /**
             * Wind From
             * @description Compass point the wind comes from
             */
            wind_from: string | null;
            /** Wind Gusts Kmh */
            wind_gusts_kmh: number | null;
            /** Wind Speed Kmh */
            wind_speed_kmh: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_auth_callback_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_now_auth_me_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    boundary_boundary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parcel_cadastre_parcel_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snap_cadastre_snap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_fields_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fire_events_fire_events_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FireEventStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FireEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    portfolio_portfolio_get: {
        parameters: {
            query?: {
                /** @description key:value; every tag must match */
                tag?: string[] | null;
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_risk_status_risk_events__risk_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskStatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_color_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagColorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list__territories_get: {
        parameters: {
            query?: {
                /** @description key:value; every tag must match */
                tag?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_territories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerritoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_territories__territory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_territories__territory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomalies_territories__territory_id__anomalies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fire_history_territories__territory_id__fire_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FireHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_outline_territories__territory_id__outline_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_events_territories__territory_id__risk_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_settings_territories__territory_id__settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_territories__territory_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_image_territories__territory_id__snapshots__day___view__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
                day: string;
                view: "true_color" | "greenness";
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spray_conditions_territories__territory_id__spray_conditions_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprayHourOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_tags_territories__territory_id__tags_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                territory_id: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerritoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tile_tiles__layer___z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: components["schemas"]["Layer"];
                z: number;
                x: number;
                y: number;
            };
            cookie?: {
                fw_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
