"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 20:00:23.892076

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fire_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "low",
                "nominal",
                "high",
                name="confidence",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("max_frp_mw", sa.Float(), nullable=True),
        sa.Column("sensors", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "STALE",
                "CLOSED",
                name="fireeventstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("processing_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fire_event")),
    )
    op.create_index(
        "ix_fire_event_geom", "fire_event", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        op.f("ix_fire_event_last_detected_at"), "fire_event", ["last_detected_at"], unique=False
    )
    op.create_index(op.f("ix_fire_event_status"), "fire_event", ["status"], unique=False)
    op.create_table(
        "ingestion_run",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("product", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCESS",
                "FAILED",
                name="runstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inserted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_run")),
    )
    op.create_index(
        op.f("ix_ingestion_run_finished_at"), "ingestion_run", ["finished_at"], unique=False
    )
    op.create_index(op.f("ix_ingestion_run_provider"), "ingestion_run", ["provider"], unique=False)
    op.create_table(
        "observation",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("product", sa.String(length=40), nullable=False),
        sa.Column("satellite", sa.String(length=30), nullable=False),
        sa.Column("sensor", sa.String(length=20), nullable=False),
        sa.Column("native_id", sa.String(length=100), nullable=True),
        sa.Column("dedup_key", sa.String(length=40), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence_raw", sa.String(length=10), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "low",
                "nominal",
                "high",
                name="confidence",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("frp_mw", sa.Float(), nullable=True),
        sa.Column("brightness_k", sa.Float(), nullable=True),
        sa.Column("day_night", sa.String(length=1), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_observation_dedup_key")),
    )
    op.create_index(
        op.f("ix_observation_acquired_at"), "observation", ["acquired_at"], unique=False
    )
    op.create_index(
        "ix_observation_geom", "observation", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "uq_observation_native_id",
        "observation",
        ["source", "native_id"],
        unique=True,
        postgresql_where=sa.text("native_id IS NOT NULL"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
        sa.UniqueConstraint(
            "owner",
            "key",
            "value",
            name=op.f("uq_tag_owner_key_value"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "territory",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "FIELD",
                "SECTION",
                name="territorykind",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("hectares", sa.Float(), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["territory.id"],
            name=op.f("fk_territory_parent_id_territory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_territory")),
    )
    op.create_index(
        "ix_territory_geom", "territory", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_territory_owner"), "territory", ["owner"], unique=False)
    op.create_index(op.f("ix_territory_parent_id"), "territory", ["parent_id"], unique=False)
    op.create_table(
        "field_risk_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("territory_id", sa.BigInteger(), nullable=False),
        sa.Column("fire_event_id", sa.BigInteger(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("bearing_deg", sa.Float(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "CRITICAL",
                "VERY_HIGH",
                "HIGH",
                "WATCH",
                name="severity",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "SEEN",
                "RESOLVED",
                name="riskstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("processing_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fire_event_id"],
            ["fire_event.id"],
            name=op.f("fk_field_risk_event_fire_event_id_fire_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["territory_id"],
            ["territory.id"],
            name=op.f("fk_field_risk_event_territory_id_territory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_risk_event")),
        sa.UniqueConstraint(
            "territory_id",
            "fire_event_id",
            name=op.f("uq_field_risk_event_territory_id_fire_event_id"),
        ),
    )
    op.create_index(
        op.f("ix_field_risk_event_fire_event_id"),
        "field_risk_event",
        ["fire_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_risk_event_territory_id"), "field_risk_event", ["territory_id"], unique=False
    )
    op.create_table(
        "observation_event_link",
        sa.Column("observation_id", sa.BigInteger(), nullable=False),
        sa.Column("fire_event_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processing_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fire_event_id"],
            ["fire_event.id"],
            name=op.f("fk_observation_event_link_fire_event_id_fire_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
            name=op.f("fk_observation_event_link_observation_id_observation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_observation_event_link")),
    )
    op.create_index(
        op.f("ix_observation_event_link_fire_event_id"),
        "observation_event_link",
        ["fire_event_id"],
        unique=False,
    )
    op.create_table(
        "spray_assessment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("territory_id", sa.BigInteger(), nullable=False),
        sa.Column("profile", sa.String(length=50), nullable=False),
        sa.Column("valid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "FAVORABLE",
                "CAUTION",
                "UNFAVORABLE",
                name="spraystatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weather", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "data_quality",
            sa.Enum(
                "GOOD",
                "PARTIAL",
                "STALE",
                "CLOUD_OBSCURED",
                "NO_DATA",
                name="dataquality",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("forecast_fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_version", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["territory_id"],
            ["territory.id"],
            name=op.f("fk_spray_assessment_territory_id_territory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spray_assessment")),
        sa.UniqueConstraint(
            "territory_id",
            "profile",
            "valid_at",
            name=op.f("uq_spray_assessment_territory_id_profile_valid_at"),
        ),
    )
    op.create_index(
        op.f("ix_spray_assessment_territory_id"), "spray_assessment", ["territory_id"], unique=False
    )
    op.create_table(
        "territory_tag",
        sa.Column("territory_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("fk_territory_tag_tag_id_tag"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["territory_id"],
            ["territory.id"],
            name=op.f("fk_territory_tag_territory_id_territory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("territory_id", "tag_id", name=op.f("pk_territory_tag")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("territory_tag")
    op.drop_index(op.f("ix_spray_assessment_territory_id"), table_name="spray_assessment")
    op.drop_table("spray_assessment")
    op.drop_index(
        op.f("ix_observation_event_link_fire_event_id"), table_name="observation_event_link"
    )
    op.drop_table("observation_event_link")
    op.drop_index(op.f("ix_field_risk_event_territory_id"), table_name="field_risk_event")
    op.drop_index(op.f("ix_field_risk_event_fire_event_id"), table_name="field_risk_event")
    op.drop_table("field_risk_event")
    op.drop_index(op.f("ix_territory_parent_id"), table_name="territory")
    op.drop_index(op.f("ix_territory_owner"), table_name="territory")
    op.drop_index("ix_territory_geom", table_name="territory", postgresql_using="gist")
    op.drop_table("territory")
    op.drop_table("tag")
    op.drop_index(
        "uq_observation_native_id",
        table_name="observation",
        postgresql_where=sa.text("native_id IS NOT NULL"),
    )
    op.drop_index("ix_observation_geom", table_name="observation", postgresql_using="gist")
    op.drop_index(op.f("ix_observation_acquired_at"), table_name="observation")
    op.drop_table("observation")
    op.drop_index(op.f("ix_ingestion_run_provider"), table_name="ingestion_run")
    op.drop_index(op.f("ix_ingestion_run_finished_at"), table_name="ingestion_run")
    op.drop_table("ingestion_run")
    op.drop_index(op.f("ix_fire_event_status"), table_name="fire_event")
    op.drop_index(op.f("ix_fire_event_last_detected_at"), table_name="fire_event")
    op.drop_index("ix_fire_event_geom", table_name="fire_event", postgresql_using="gist")
    op.drop_table("fire_event")
    # ### end Alembic commands ###
