"""goes cursor and lightning flashes

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 21:38:26.643617

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lightning_flash",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("native_id", sa.String(length=60), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("energy_j", sa.Float(), nullable=False),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lightning_flash")),
        sa.UniqueConstraint("native_id", name=op.f("uq_lightning_flash_native_id")),
    )
    op.create_index(
        "ix_lightning_flash_geom",
        "lightning_flash",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_lightning_flash_observed_at"), "lightning_flash", ["observed_at"], unique=False
    )
    op.add_column("ingestion_run", sa.Column("cursor", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingestion_run", "cursor")
    op.drop_index(op.f("ix_lightning_flash_observed_at"), table_name="lightning_flash")
    op.drop_index("ix_lightning_flash_geom", table_name="lightning_flash", postgresql_using="gist")
    op.drop_table("lightning_flash")
    # ### end Alembic commands ###
