"""historical detections

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 09:42:10.016984

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_detection",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product", sa.String(length=30), nullable=False),
        sa.Column("dedup_key", sa.String(length=40), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "low",
                "nominal",
                "high",
                name="confidence",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("frp_mw", sa.Float(), nullable=True),
        sa.Column("day_night", sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_detection")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_historical_detection_dedup_key")),
    )
    op.create_index(
        op.f("ix_historical_detection_acquired_at"),
        "historical_detection",
        ["acquired_at"],
        unique=False,
    )
    op.create_index(
        "ix_historical_detection_geom",
        "historical_detection",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_historical_detection_geom", table_name="historical_detection", postgresql_using="gist"
    )
    op.drop_index(op.f("ix_historical_detection_acquired_at"), table_name="historical_detection")
    op.drop_table("historical_detection")
    # ### end Alembic commands ###
