"""static heat sources

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 19:41:48.341046

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "static_source",
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("detections", sa.Integer(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("latitude", "longitude", name=op.f("pk_static_source")),
    )
    op.create_index(
        "ix_static_source_geom", "static_source", ["geom"], unique=False, postgresql_using="gist"
    )
    op.add_column(
        "observation",
        sa.Column("static_source", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observation", "static_source")
    op.drop_index("ix_static_source_geom", table_name="static_source", postgresql_using="gist")
    op.drop_table("static_source")
    # ### end Alembic commands ###
