"""cadastral parcels

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 19:59:23.071028

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cadastral_parcel",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("province", sa.String(length=60), nullable=False),
        sa.Column("department", sa.Integer(), nullable=False),
        sa.Column("partida", sa.BigInteger(), nullable=False),
        sa.Column("plano", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cadastral_parcel")),
        sa.UniqueConstraint(
            "province",
            "department",
            "partida",
            name=op.f("uq_cadastral_parcel_province_department_partida"),
        ),
    )
    op.create_index(
        "ix_cadastral_parcel_geom",
        "cadastral_parcel",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "cadastral_tile",
        sa.Column("province", sa.String(length=60), nullable=False),
        sa.Column("z", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("parcels", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("province", "z", "x", "y", name=op.f("pk_cadastral_tile")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cadastral_tile")
    op.drop_index(
        "ix_cadastral_parcel_geom", table_name="cadastral_parcel", postgresql_using="gist"
    )
    op.drop_table("cadastral_parcel")
    # ### end Alembic commands ###
